#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:
          cat >> .config <<EOF
          # 编译x64固件:
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_HAS_SUBTARGETS=y
          CONFIG_HAS_DEVICES=y
          CONFIG_TARGET_BOARD="x86"
          CONFIG_TARGET_SUBTARGET="64"
          CONFIG_TARGET_PROFILE="DEVICE_generic"
          CONFIG_TARGET_ARCH_PACKAGES="x86_64"
          # VMware镜像
          CONFIG_VMDK_IMAGES=y
          CONFIG_TARGET_IMAGES_PAD=y
          # 固件压缩配置:
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_TARGET_KERNEL_PARTSIZE=16
          CONFIG_TARGET_ROOTFS_PARTSIZE=960

          # IPv6支持:
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y

          # 多文件系统支持:
          # CONFIG_PACKAGE_kmod-fs-9p is not set
          # CONFIG_PACKAGE_kmod-fs-afs is not set
          # CONFIG_PACKAGE_kmod-fs-autofs4 is not set
          # CONFIG_PACKAGE_kmod-fs-btrfs is not set
          # CONFIG_PACKAGE_kmod-fs-cifs is not set
          # CONFIG_PACKAGE_kmod-fs-configfs is not set
          # CONFIG_PACKAGE_kmod-fs-cramfs is not set
          # CONFIG_PACKAGE_kmod-fs-efivarfs is not set
          CONFIG_PACKAGE_kmod-fs-exfat=y
          # CONFIG_PACKAGE_kmod-fs-exportfs is not set
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-f2fs=y
          # CONFIG_PACKAGE_kmod-fs-fscache is not set
          # CONFIG_PACKAGE_kmod-fs-hfs is not set
          # CONFIG_PACKAGE_kmod-fs-hfsplus is not set
          # CONFIG_PACKAGE_kmod-fs-isofs is not set
          # CONFIG_PACKAGE_kmod-fs-jfs is not set
          # CONFIG_PACKAGE_kmod-fs-ksmbd is not set
          # CONFIG_PACKAGE_kmod-fs-minix is not set
          # CONFIG_PACKAGE_kmod-fs-msdos is not set
          # CONFIG_PACKAGE_kmod-fs-netfs is not set
          # CONFIG_PACKAGE_kmod-fs-nfs is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-common is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-ssc is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v3 is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v4 is not set
          # CONFIG_PACKAGE_kmod-fs-nfsd is not set
          # CONFIG_PACKAGE_kmod-fs-ntfs is not set
          CONFIG_PACKAGE_kmod-fs-ntfs3=y
          # CONFIG_PACKAGE_kmod-fs-reiserfs is not set
          # CONFIG_PACKAGE_kmod-fs-squashfs is not set
          # CONFIG_PACKAGE_kmod-fs-udf is not set
          CONFIG_PACKAGE_kmod-fs-vfat=y
          # CONFIG_PACKAGE_kmod-fs-virtiofs is not set
          # CONFIG_PACKAGE_kmod-fs-xfs is not set
          # CONFIG_PACKAGE_kmod-fuse is not set
          # end of Filesystems

          # USB3.0支持:
          # CONFIG_PACKAGE_kmod-usb-ohci is not set
          # CONFIG_PACKAGE_kmod-usb-ohci-pci is not set
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y

          # 常用库
          CONFIG_PACKAGE_adguardhome=y
          CONFIG_PACKAGE_adbyby=y

          # 常用LuCI插件选择:
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-dnsfilter=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-adguardhome=y
          CONFIG_PACKAGE_luci-app-adguardhome_INCLUDE_binary=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-acme=y

          # CONFIG_PACKAGE_luci-app-aria2 is not set
          # CONFIG_PACKAGE_baidupcs-web is not set
          # CONFIG_PACKAGE_python3-docker is not set
          # CONFIG_PACKAGE_luci-app-frpc is not set
          # CONFIG_PACKAGE_luci-app-kodexplorer is not set
          # CONFIG_PACKAGE_luci-app-minidlna is not set
          # CONFIG_PACKAGE_luci-app-openvpn is not set
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-aliyundrive-webdav=y
          CONFIG_PACKAGE_luci-app-accesscontrol=y

          CONFIG_PACKAGE_luci-app-ssr-plus=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_NaiveProxy is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_IPT2Socks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2 is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Rust_Server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_Plugin is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y

          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_Transparent_Proxy=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_IPv6_Nat=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_NaiveProxy is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_PDNSD=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray_Plugin is not set

          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE=y
          CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_BBR_CCA=y
          # CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_DNSFORWARDER is not set
          # CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_DNSPROXY is not set

          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go=y
          CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_NodeJS=y
          # CONFIG_PACKAGE_luci-app-unblockneteasemusic is not set

          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_luci-app-verysync is not set
          # CONFIG_PACKAGE_luci-app-webadmin is not set
          # CONFIG_PACKAGE_luci-app-wireguard is not set
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-softethervpn=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          # CONFIG_PACKAGE_luci-app-gost is not set
          CONFIG_PACKAGE_luci-app-advancedsetting=y
          # CONFIG_PACKAGE_luci-app-openclash is not set

          CONFIG_PACKAGE_luci-app-store=y

          # LuCI主题:
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-theme-argon_new=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          CONFIG_PACKAGE_luci-theme-opentomcat=y
          CONFIG_PACKAGE_luci-theme-opentomato=y
          
          # 常用软件包:
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_vim-fuller=y
          CONFIG_PACKAGE_wget-ssl=y

          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
